services:
  postgres:
    restart: always
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - prod_db:/var/lib/postgresql/data
    networks:
      - caddy

  api:
    image: docker.io/miromlynarik/vce-api:prod
    container_name: api
    environment:
      - BACKEND_DB_USER=postgres
      - BACKEND_DB_NAME=postgres
      - BACKEND_DB_PASSWORD=postgres
      - BACKEND_DB_HOST=postgres
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always
    networks:
      - caddy

  web:
    image: docker.io/miromlynarik/vce-web:prod
    container_name: web
    environment:
      - BACKEND_API_URL=http://api:8000/api
      - JWT_SECRET_KEY=G349D3/i12FVOZ2QyvQ8yZPTppgmw8XFBH6VTCkAofE=
      - GITHUB_CLIENT_ID=Ov23liNAnBUWffr5VN7O
      - GITHUB_CLIENT_SECRET=15ef5fc0a21687a031cf5d0206f5749493df232c
      - GITHUB_REDIRECT_URL=http://mmlynarik.com:3000/api/oauth/github
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - api
    restart: always
    networks:
      - caddy

  caddy:
    image: caddy:2.10
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - caddy

volumes:
  prod_db:
  caddy_data:

networks:
  caddy:
