services:
  db:
    restart: always
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - prod_db:/var/lib/postgresql/data
    networks:
      - caddy

  api:
    image: docker.io/miromlynarik/vce-api:prod
    container_name: api
    environment:
      - BACKEND_DB_USER=postgres
      - BACKEND_DB_NAME=postgres
      - BACKEND_DB_PASSWORD=postgres
      - BACKEND_DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    networks:
      - caddy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  django:
    image: docker.io/miromlynarik/pokedex-api:prod
    container_name: django
    environment:
      - BACKEND_DB_USER=postgres
      - BACKEND_DB_NAME=postgres
      - BACKEND_DB_PASSWORD=postgres
      - BACKEND_DB_HOST=db
      - USEDB=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USER=admin
      - DJANGO_SUPERUSER_EMAIL=
    ports:
      - 9000:8000
    depends_on:
      - db
    restart: always
    networks:
      - caddy

  web:
    image: docker.io/miromlynarik/vce-web:prod
    container_name: web
    environment:
      - BACKEND_API_URL=http://api:8000/api
      - JWT_SECRET_KEY=G349D3/i12FVOZ2QyvQ8yZPTppgmw8XFBH6VTCkAofE=
      - GITHUB_CLIENT_ID=Ov23liNAnBUWffr5VN7O
      - GITHUB_CLIENT_SECRET=15ef5fc0a21687a031cf5d0206f5749493df232c
      - GITHUB_REDIRECT_URL=http://mmlynarik.com/api/oauth/github
    ports:
      - 3000:3000
    depends_on:
      - db
      - api
    restart: always
    networks:
      - caddy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: caddy:2.10
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - caddy

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "60"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  prod_db:
  caddy_data:

networks:
  caddy:
