import type {Metadata} from "next";
import fontLocal from "next/font/local";
import "./globals.css";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app ",
};

const coinBaseSans = fontLocal({
    src: "../../public/fonts/Coinbase-Sans-Regular.woff2",
    variable: "--font-coinbase",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${coinBaseSans.variable} antialiased font-sans h-screen`}>{children}</body>
        </html>
    );
}
